### ISSUE TITLE
Support for PKCE

### ISSUE THREAD

**Issue by mk53202** [kolitiri/fastapi-oidc-react#9]
Has anyone got this pattern and example woerking with PKCE?

I'm getting the dreaded:
Proof Key for Code Exchange is required for cross-origin authorization code redemption.

**Comment by kolitiri** [comment]
Hi @mk53202 

Not really sure cause I didn't run into the same issue myself, but sounds like you might have misconfigured the redirect urls on Azure.

This might help:
https://learn.microsoft.com/en-us/answers/questions/1194524/how-to-fix-aadsts9002325-proof-key-for-code-exchan
